[package]
name = "make87"
version = "0.0.0"
authors = ["Nisse Knudsen <nisse@make87.com>", "Phillip Thomas <phillip@make87.com>"]
edition = "2021"
homepage = "https://www.make87.com"
repository = "https://github.com/make87/make87-rust"
license-file = "LICENSE"
description = "Rust SDK for make87 platform."

[dependencies]
once_cell = "1.20.2"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
thiserror = "2.0.12"
tokio = { version = "1.16.1", features = ["time"] }
zenoh = { version = "1.2.1", features = ["unstable"] }
log = "0.4.22"
make87_messages = ">=0.1.0"
gag = "1.0.0"