[package]
name = "make87"
version = "0.0.0"
authors = ["Nisse Knudsen <nisse@make87.com>", "Phillip Thomas <phillip@make87.com>"]
edition = "2021"
homepage = "https://www.make87.com"
license-file = "LICENSE"
description = "Rust SDK for make87 platform."

[dependencies]
once_cell = "1.20.2"
prost = "0.13"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
thiserror = "1.0.63"
tokio = { version = "1.16.1", features = ["time"] }
zenoh = { version = "1.2.1", features = ["unstable"] }
log = "0.4.22"
make87_messages = "^0.0.94"
gag = "1.0.0"